name: "net4home Server"
description: "Add-on für das net4home Bussystem - Das Add-on stellt die Verbindung zu dem net4home Bussystem über die serielle Schnittstelle her. net4home Clients können sich dann per IP-Verbindung dann mit dem Bus verbinden."
version: "1.0.4"
slug: "net4home"
url: "https://github.com/anynode/n4hSvc"
init: false
host_network: true
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
startup: "services"
boot: "auto"
uart: true
usb: true
full_access: true
privileged:
  - SYS_ADMIN
  - SYS_RAWIO
  - NET_ADMIN
ports:
  3478/tcp: 3478
ports_description:
  3478/tcp: "TCP/IP Port für net4home Client-Verbindungen"
options:
  loglevel: 0
  port: 3478
  comport: "/dev/ttyUSB0"
  ipv6: false
  enableHSTime: false
  enableHSPacketRouter: false
schema:
  loglevel: int(0,10)
  port: port
  comport: str
  ipv6: bool
  enableHSTime: bool
  enableHSPacketRouter: bool
watchdog: "tcp://[HOST]:[PORT:3478]"