name: "net4home Server"
description: "Add-on f체r den net4home Server (n4hSvc) - Ein Server f체r die Kommunikation mit net4home Ger채ten 체ber serielle Schnittstelle."
version: "1.3.0"
slug: "net4home"
init: false
host_network: true
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
startup: "services"
boot: "auto"
uart: true
usb: true
full_access: true
privileged:
  - SYS_ADMIN
  - SYS_RAWIO
  - NET_ADMIN
options:
  loglevel: "0 - Only Errors"
  port: 3478
  comport: "/dev/ttyUSB0"
  noPasswords: true
  ipv6: false
  passwords: []
schema:
  loglevel: "select(0 - Only Errors|9 - Errors and Buspackets|10 - All)"
  port: "int"
  comport: "str"
  noPasswords: "bool"
  ipv6: "bool"
  passwords:
    - "str"
