name: "net4home Server"
description: "Add-on für das net4home Bussystem - Das Add-on stellt die Verbindung zu dem net4home Bussystem über die serielle Schnittstelle her. net4home Clients können sich dann per IP-Verbindung dann mit dem Bus verbinden."
version: "1.3.4"
slug: "net4home"
init: false
host_network: true
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
startup: "services"
boot: "auto"
uart: true
usb: true
full_access: true
privileged:
  - SYS_ADMIN
  - SYS_RAWIO
  - NET_ADMIN
options:
  loglevel: 0
  port: 3478
  comport: "/dev/ttyUSB0"
  noPasswords: true
  ipv6: false
  passwords: []
  enableHSTime: false
schema:
  loglevel: int(0,10)
  port: port
  comport: str
  noPasswords: bool
  ipv6: bool
  passwords: [str]
  enableHSTime: bool
